USER_COLOR = "user"
SONG_COLOR = "song"

WALK = "camino"
MOST_IMPORTANTS = "mas_importantes"
RECOMENDATION = "recomendacion"
CYCLE = "ciclo"
RANGE = "rango"
CLUSTERING = "clustering"

COMMANDS = [WALK, MOST_IMPORTANTS, RECOMENDATION, CYCLE, RANGE, CLUSTERING]

WALK_PARAMETERS_COUNT = 2
MOST_IMPORTANTS_PARAMETER_COUNT = 1
RECOMENDATION_PARAMETER_COUNT = 3
CYCLE_PARAMETER_COUNT = 2
RANGE_PARAMETER_COUNT = 2
CLUSTERING_PARAMETER_COUNT = 1