ERROR_INPUT = 'ERROR: Entrada Invalida'
ERROR_CMD = 'ERROR: Comando Ingresado Invalido (no existe o esta mal escrito)'
ERROR_PARAM_COUNT = 'ERROR: Cantidad de Parametros Invalida para este Comando'
ERROR_INVALID_SONG = 'Tanto el origen como el destino deben ser canciones'
ERROR_PATH_NOT_FOUND = 'No se encontro recorrido'